quarkus:
  application:
    name: quarkus-reactive-dev
    version: dev
  devservices:
    enabled: true
  datasource:
    db-kind: mysql
    username: quarkus-user
    password: quarkus-password
    reactive:
      ~: true
      url: mysql://localhost:3306/quarkus
      max-size: 20
      reconnect-attempts: 3
      cache-prepared-statements: true
